# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "436eec537e8f59d6140673d74c659fae"
name = "template-ruby"
handle = "template-ruby-1"
application_url = "https://localhost:60803"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://localhost:60803/auth/callback",
  "https://localhost:60803/auth/shopify/callback",
  "https://localhost:60803/api/auth/callback"
]

[pos]
embedded = false
web_directories = [ "web/frontend", "web" ]
