# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0dc87d78fddd59cf49787ed52844b377"
name = "template-ruby"
handle = "template-ruby-1"
application_url = "https://budget-languages-opening-discounted.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://budget-languages-opening-discounted.trycloudflare.com/auth/callback", "https://budget-languages-opening-discounted.trycloudflare.com/auth/shopify/callback", "https://budget-languages-opening-discounted.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
web_directories = [ "web/frontend", "web" ]
